---
services:
  webtop:
    image: lscr.io/linuxserver/webtop:latest
    container_name: webtop
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
    volumes:
      - ./config:/config
      - /var/run/docker.sock:/var/run/docker.sock #optional
      - ..:/workspace:cached
    ports:
      - 3000:3000
      #- 3001:3001
    #devices:
    #  - /dev/dri:/dev/dri #optional
    shm_size: "1gb" #optional
    restart: unless-stopped
